.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.\"See Also:
.\"man mdoc.samples for a complete listing of options
.\"man mdoc for the short list of editing options
.\"/usr/share/misc/mdoc.template
.Dd 1/27/2012
.Dt bsreplace 1
.Os Darwin
.Sh NAME
.Nm bsreplace
.Nd Insert, overwrite, or find-and-replace bytes.
.Sh SYNOPSIS
.Nm
.Op Fl r                \" allow resize
.Op Fl m                \" allow multiple 
.Op Fl i Ar offset bytes
.Op Fl s Ar offset bytes
.Op Fl f Ar old_bytes new_bytes
.Op Fl o Ar outfile
.Ar file
.Sh DESCRIPTION
Insert, overwrite, or find-and-replace bytes. By default, find-and-replace requires
the search bytes to be unique and the counts of the search and the replacement bytes
must be equal. Inserting implies the size will change; overwriting implies the
size will not change.
.Pp
A list of flags and their descriptions:
.Bl -tag -width -indent
.It Fl r
Allow resizing.
.It Fl m
Allow multiple occurrences to be be replaced.
.It Fl i Ar offset bytes
Inserts bytes at offset bytes from the beginning of the file.
.It Fl s Ar offset bytes
Substitute bytes beginning at the file offset with "bytes".
.It Fl f Ar old_bytes new_bytes
Find "old_bytes" and replace with "new_bytes". 
.It Fl o Ar outfile
Write the output to outfile instead of overwriting the input file.
.El
.Pp
.Sh SEE ALSO 
.Xr bsdiff 1 , 
.Xr bspatch 1
.\" .Sh BUGS

.\" .Sh HISTORY           \" Document history if command behaves in a unique manner